# Generated by Django 4.2.4 on 2023-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date'], name='publication_date_53107d_idx'),
        ),
    ]
