# Generated by Django 4.2.4 on 2023-09-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Url тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TagsToPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.post', verbose_name='Публикация')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.tag', verbose_name='Тег')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='publications.TagsToPosts', to='publications.tag', verbose_name='Теги'),
        ),
        migrations.AddConstraint(
            model_name='tagstoposts',
            constraint=models.UniqueConstraint(fields=('tag', 'post'), name='unique_post_tag'),
        ),
    ]
