# Generated by Django 4.2.4 on 2023-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_tag_tagstoposts_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='publications.tag', verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='TagsToPosts',
        ),
    ]
