# Generated by Django 4.2.4 on 2023-09-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_post_tags_delete_tagstoposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsToPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.post', verbose_name='Публикация')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.tag', verbose_name='Тег')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='publications.TagsToPosts', to='publications.tag', verbose_name='Теги'),
        ),
        migrations.AddConstraint(
            model_name='tagstoposts',
            constraint=models.UniqueConstraint(fields=('tag', 'post'), name='unique_post_tag'),
        ),
    ]
