# Generated by Django 4.2.4 on 2023-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Url тега'),
        ),
    ]
